### PR TITLE
CMake Fixup

### LINKED ISSUE #119: Strange include in CMake CFLAGS
/usr/bin/c++   -DPD_VERSION=\"v0.3.0-65-gb9b8635\" -DWITH_MP3 -DWITH_SNDFILE **-I/home/vagrant/ury-playd/playd** -I/usr/include/SDL2 **-I/home/vagrant/ury-playd/playd_tests**  -std=c++14   -o CMakeFiles/playd.dir/src/main.cpp.o -c /home/vagrant/ury-playd/src/main.cpp

I'm not sure where these are coming from. If you run cmake from outside of the git root, the includes are benign, but if you run it inside, those paths are the output paths of the `playd` and `playd_tests` binaries. This generates annoying warnings if either exists:

`cc1plus: warning: /home/vagrant/ury-playd/playd: not a directory`

### LINKED ISSUE #121: cmake: libuv missing does not kill build
Current behaviour:

```
-- Enabling '-std=c++14' C++ compiler flag.
-- Using C++14 compatible compiler: Clang.
-- Enabling '-fPIC' C compiler flag.
-- CXX compilation flags:  -std=c++14.
-- C compilation flags:  -fPIC.
-- Could NOT find LIBUV (missing:  LIBUV_LIBRARIES LIBUV_INCLUDE_DIR)
-- Supported formats: MP3;OGG;WAV;FLAC
-- Linking: SDL2_LIBRARY /usr/local/lib/libSDL2main.a;/usr/local/lib/libSDL2.dylib;-framework Cocoa
-- Linking: MPG123_LIBRARIES /usr/local/lib/libmpg123.dylib
-- Linking: SNDFILE_LIBRARY /usr/local/lib/libsndfile.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mattbw/Documents/git/ury-playd
```

Expected behaviour: don't write build files when libuv is missing—we can't actually build playd without it.

### PR DESCRIPTION
**Pull request by DinCahill**
- [x] Formatting and some rearrangement.
- [x] Fix #119.
- [x] Fix #121.
- [x] Add compiler warning flags.
- [x] Make Sugar a subtree instead of a submodule?

Catch has been updated to fix a warning on gcc.

### CODE REVIEW

**Comment by LordAro** [comment]
If I was being picky, I'd ask that all 5 of those points were split into separate PRQs :p

I'm not sure about this Sugar thing, and certainly not sure about it being a subtree rather than a submodule. Can you expand on your reasoning for it?

**Comment by DinCahill** [comment]
@CaptainHayashi and I thought making subtrees out of Sugar and the GSL (in his branch) would avoid noobs having problems by not getting the submodules. I do see the downsides too. I have no strong feelings one way or the other.

Sugar is quite large, and I'm not using most of it. My justification for it isn't terribly strong. My personal style is to pull in modules rather than write essentially the same thing myself.

I'm currently not touching the warning flags for the MSVC build, because I'm not sure what I want to do with it yet.

Sugar also has a module for collecting source files, because the standard ways of globbing your source files don't work well in CMake (which is why we currently list every source file). I'll look into it.

**Comment by CaptainHayashi** [comment]
What @DinCahill said—we've tangled ourselves in knots in URY with submodules before, and it doesn't at all seem worth it in this case.  What exactly are the disadvantages to using subtree merge over submodules?

**Comment by MattWindsor91** [comment]
@DinCahill is this ready to merge?  It's been sitting here for a while

**Comment by DinCahill** [comment]
Ready other than the subtree/submodule issue.

**Comment by LordAro** [comment]
Still not a fan of the subtree, I think. Although I don't actually care, so do whatever :p

**Comment by DinCahill** [comment]
I'll update libraries in separate commits in future ❤️

**Comment by LordAro** [comment]
But muh history

**Comment by MattWindsor91** [comment]
Can we merge this?

**Comment by LordAro** [comment]
don't care anymore

**Pull request merged**
